name: Playwright Tests

on:
  workflow_dispatch:
    inputs: 
      branch:
        description: 'Branch to run tests'
        required: true
        default: 'main'
      browser:
        description: 'Browser to run tests'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js    
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

       # Install system dependencies only if browser == webkit
      - name: Install Playwright deps for WebKit
        if: ${{ github.event.inputs.browser == 'webkit' }}
        run: npx playwright install-deps

      - name: Install Playwright Browser
        run: npx playwright install ${{ github.event.inputs.browser }}

      - name: Run Playwright tests
        run: npx playwright test --project=${{ github.event.inputs.browser }}

      - name: Upload Playwright report as artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

